CREATE TABLE air_canary.air_now_forecast_area (
    reporting_area varchar(45) NOT NULL,
    state_code char(2) not null,
    country_code char(2) not null,
    forecasts varchar(3),
    action_day varchar(50),
    latitude varchar(9),
    longitude varchar(11),
    gmt_offset tinyint(1),
    daylight_savings varchar(3),
    standard_time_label varchar(3),
    daylight_time_label varchar(3),
    twc_code varchar(5),
    usa_today varchar(3),
    forecast_source varchar(100),
    primary key (reporting_area, state_code, country_code),
    index (state_code),
    index (country_code, state_code)
) engine = inndob;

CREATE TABLE air_canary.air_now_monitoring_site (
    aqsid char(9) not null,
    parameter varchar(10) not null,
    site_code char(4),
    site_name varchar(20),
    status varchar(8),
    agency_id varchar(4),
    agency_name varchar(60),
    epa_region char(2),
    latitude varchar(9),
    longitude varchar(11),
    elevation int,
    gmt_offset tinyint(1),
    country_code char(2),
    cmsa_code char(4),
    cmsa_name varchar(50),
    msa_code char(4),
    msa_name varchar(50),
    state_code char(2),
    state_name char(2),
    county_code char(9),
    county_name varchar(25),
    city_code char(9),
    primary key (aqsid, parameter),
    index (site_name),
    index (state_name),
    index (country_code, state_name),
    index (latitude, longitude),
    index (parameter)
) engine = innodb;
